services:
  - type: web
    name: shopify-review-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shopify_backend_app:app
    envVars:
      - key: SHOPIFY_SHOP_DOMAIN
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false